PyLatein/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import Vokabel.urls
import Trainer.urls

import Vokabel.views

urlpatterns = [
    url(r"^$", Vokabel.views.AllVoc.as_view(), name="index"),
    url(r"^vokabel/", include(Vokabel.urls)),
    url(r"^trainer/", include(Trainer.urls)),
    url(r"^admin/", include(admin.site.urls)),
]

Trainer/urls.py
from django.conf.urls import url
import Trainer.views

app_name = "trainer"
urlpatterns = [
    url(r"^$", Trainer.views.TrainerView.as_view(), name="trainer"),
    url(r"^select$", Trainer.views.VocSelectionView.as_view(), name="select"),
]

Vokabel/urls.py
from django.conf.urls import url
import Vokabel.views

app_name="vokabel"
urlpatterns = [
    url(r"search", Vokabel.views.SearchView.as_view(), name="search"),
    url(r"createNoun$", Vokabel.views.CreateNoun.as_view(), name="create_noun"),
    url(r"noun(?P<pk>[0-9]+)$", Vokabel.views.NounDetail.as_view(), name="view_noun"),
    url(r"createVerb$", Vokabel.views.CreateVerb.as_view(), name="create_verb"),
    url(r"verb(?P<pk>[0-9]+)$", Vokabel.views.VerbDetail.as_view(), name="view_verb"),
    url(r"createAdjective$", Vokabel.views.CreateAdjective.as_view(), name="create_adjective"),
    url(r"adjective(?P<pk>[0-9]+)$", Vokabel.views.AdjectiveDetail.as_view(), name="view_adjective"),
    url(r"createVocGr$", Vokabel.views.CreateVocGroup.as_view(), name="create_vocgroup"),
]

Vokabel/models.py
from django.db import models
import enum

class Genus(enum.Enum):
    masculine, feminine, neuter = "m", "f", "n"

class Case(enum.Enum):
    (sg1, sg2, sg3, sg4, sg5, sg6,
    pl1, pl2, pl3, pl4, pl5, pl6) = range(1, 13)

class Person(enum.Enum):
    (sg1, sg2, sg3,
    pl1, pl2, pl3) = range(1, 7)

class Declination(enum.Enum):
    A="A-Declination"
    O="O-Declination"
    C="3. Declination Consonant Stems"
    M="3. Declination Mixed Stems"
    I="3. Declination I-Stems"
    E="E-Declination"
    U="U-Declination"

class Conjugation(enum.Enum):
    A="A-Conjugation"
    E="E-Conjugation"
    C="Consonant Conjugation"
    I="I-Conjugation"
    M="Mixed Conjugation"
    N="None"

class AdjDeclination(enum.Enum):
    AO="A/O - Declination"
    M="Mixed (3.) Declination"

class Tense(enum.Enum):
    present, perfect, imperfect, pluqperfect, future=range(5)


class Vocable(models.Model):
    translation=models.CharField(max_length=128)
    class Meta:
        abstract=True


class Noun(Vocable):
    genus=models.CharField(max_length=1,
        choices=[(g.value, g.name) for g in Genus])
    declination=models.CharField(max_length=2,
        choices=[(d.name, d.value) for d in Declination])

    #stem and ending
    sg1=models.CharField(max_length=128)
    sg2=models.CharField(max_length=128)
    sg3=models.CharField(max_length=128)
    sg4=models.CharField(max_length=128)
    sg5=models.CharField(max_length=128)
    sg6=models.CharField(max_length=128)

    pl1=models.CharField(max_length=128)
    pl2=models.CharField(max_length=128)
    pl3=models.CharField(max_length=128)
    pl4=models.CharField(max_length=128)
    pl5=models.CharField(max_length=128)
    pl6=models.CharField(max_length=128)

    def __str__(self):
        if self.sg1 == "-":
            return "{pl1}, {pl2} [{genus}] (Pl.)".format(pl1=self.pl1, pl2=self.pl2, genus=self.genus)
        else:
            return "{sg1}, {sg2} [{genus}]".format(sg1=self.sg1, sg2=self.sg2, genus=self.genus)

class Verb(Vocable):
    conjugation=models.CharField(max_length=2,
        choices=[(c.name, c.value) for c in Conjugation])

    infinitive=models.CharField(max_length=128)
    imperative_sg=models.CharField(max_length=128)
    imperative_pl=models.CharField(max_length=128)

    present_sg1=models.CharField(max_length=128)
    present_sg2=models.CharField(max_length=128)
    present_sg3=models.CharField(max_length=128)
    present_pl1=models.CharField(max_length=128)
    present_pl2=models.CharField(max_length=128)
    present_pl3=models.CharField(max_length=128)

    perfect_sg1=models.CharField(max_length=128)
    perfect_sg2=models.CharField(max_length=128)
    perfect_sg3=models.CharField(max_length=128)
    perfect_pl1=models.CharField(max_length=128)
    perfect_pl2=models.CharField(max_length=128)
    perfect_pl3=models.CharField(max_length=128)

    imperfect_sg1=models.CharField(max_length=128)
    imperfect_sg2=models.CharField(max_length=128)
    imperfect_sg3=models.CharField(max_length=128)
    imperfect_pl1=models.CharField(max_length=128)
    imperfect_pl2=models.CharField(max_length=128)
    imperfect_pl3=models.CharField(max_length=128)

    pluqperfect_sg1=models.CharField(max_length=128)
    pluqperfect_sg2=models.CharField(max_length=128)
    pluqperfect_sg3=models.CharField(max_length=128)
    pluqperfect_pl1=models.CharField(max_length=128)
    pluqperfect_pl2=models.CharField(max_length=128)
    pluqperfect_pl3=models.CharField(max_length=128)

    future_sg1=models.CharField(max_length=128)
    future_sg2=models.CharField(max_length=128)
    future_sg3=models.CharField(max_length=128)
    future_pl1=models.CharField(max_length=128)
    future_pl2=models.CharField(max_length=128)
    future_pl3=models.CharField(max_length=128)

    future2_sg1=models.CharField(max_length=128)
    future2_sg2=models.CharField(max_length=128)
    future2_sg3=models.CharField(max_length=128)
    future2_pl1=models.CharField(max_length=128)
    future2_pl2=models.CharField(max_length=128)
    future2_pl3=models.CharField(max_length=128)

    def __str__(self):
        return "{pr1}, {pr2}, {inf}, {perf}".format(pr1=self.present_sg1, pr2=self.present_sg2,
                                                    inf=self.infinitive, perf=self.perfect_sg1)

class Adjective(Vocable):
    declination=models.CharField(max_length=2,
        choices=[(d.name, d.value) for d in AdjDeclination])

    pos_sg1m=models.CharField(max_length=128)
    pos_sg2m=models.CharField(max_length=128)
    pos_sg3m=models.CharField(max_length=128)
    pos_sg4m=models.CharField(max_length=128)
    pos_sg5m=models.CharField(max_length=128)
    pos_sg6m=models.CharField(max_length=128)
    pos_pl1m=models.CharField(max_length=128)
    pos_pl2m=models.CharField(max_length=128)
    pos_pl3m=models.CharField(max_length=128)
    pos_pl4m=models.CharField(max_length=128)
    pos_pl5m=models.CharField(max_length=128)
    pos_pl6m=models.CharField(max_length=128)
    pos_sg1f=models.CharField(max_length=128)
    pos_sg2f=models.CharField(max_length=128)
    pos_sg3f=models.CharField(max_length=128)
    pos_sg4f=models.CharField(max_length=128)
    pos_sg5f=models.CharField(max_length=128)
    pos_sg6f=models.CharField(max_length=128)
    pos_pl1f=models.CharField(max_length=128)
    pos_pl2f=models.CharField(max_length=128)
    pos_pl3f=models.CharField(max_length=128)
    pos_pl4f=models.CharField(max_length=128)
    pos_pl5f=models.CharField(max_length=128)
    pos_pl6f=models.CharField(max_length=128)
    pos_sg1n=models.CharField(max_length=128)
    pos_sg2n=models.CharField(max_length=128)
    pos_sg3n=models.CharField(max_length=128)
    pos_sg4n=models.CharField(max_length=128)
    pos_sg5n=models.CharField(max_length=128)
    pos_sg6n=models.CharField(max_length=128)
    pos_pl1n=models.CharField(max_length=128)
    pos_pl2n=models.CharField(max_length=128)
    pos_pl3n=models.CharField(max_length=128)
    pos_pl4n=models.CharField(max_length=128)
    pos_pl5n=models.CharField(max_length=128)
    pos_pl6n=models.CharField(max_length=128)

    comp_sg1m=models.CharField(max_length=128)
    comp_sg2m=models.CharField(max_length=128)
    comp_sg3m=models.CharField(max_length=128)
    comp_sg4m=models.CharField(max_length=128)
    comp_sg5m=models.CharField(max_length=128)
    comp_sg6m=models.CharField(max_length=128)
    comp_pl1m=models.CharField(max_length=128)
    comp_pl2m=models.CharField(max_length=128)
    comp_pl3m=models.CharField(max_length=128)
    comp_pl4m=models.CharField(max_length=128)
    comp_pl5m=models.CharField(max_length=128)
    comp_pl6m=models.CharField(max_length=128)
    comp_sg1f=models.CharField(max_length=128)
    comp_sg2f=models.CharField(max_length=128)
    comp_sg3f=models.CharField(max_length=128)
    comp_sg4f=models.CharField(max_length=128)
    comp_sg5f=models.CharField(max_length=128)
    comp_sg6f=models.CharField(max_length=128)
    comp_pl1f=models.CharField(max_length=128)
    comp_pl2f=models.CharField(max_length=128)
    comp_pl3f=models.CharField(max_length=128)
    comp_pl4f=models.CharField(max_length=128)
    comp_pl5f=models.CharField(max_length=128)
    comp_pl6f=models.CharField(max_length=128)
    comp_sg1n=models.CharField(max_length=128)
    comp_sg2n=models.CharField(max_length=128)
    comp_sg3n=models.CharField(max_length=128)
    comp_sg4n=models.CharField(max_length=128)
    comp_sg5n=models.CharField(max_length=128)
    comp_sg6n=models.CharField(max_length=128)
    comp_pl1n=models.CharField(max_length=128)
    comp_pl2n=models.CharField(max_length=128)
    comp_pl3n=models.CharField(max_length=128)
    comp_pl4n=models.CharField(max_length=128)
    comp_pl5n=models.CharField(max_length=128)
    comp_pl6n=models.CharField(max_length=128)

    sup_sg1m=models.CharField(max_length=128)
    sup_sg2m=models.CharField(max_length=128)
    sup_sg3m=models.CharField(max_length=128)
    sup_sg4m=models.CharField(max_length=128)
    sup_sg5m=models.CharField(max_length=128)
    sup_sg6m=models.CharField(max_length=128)
    sup_pl1m=models.CharField(max_length=128)
    sup_pl2m=models.CharField(max_length=128)
    sup_pl3m=models.CharField(max_length=128)
    sup_pl4m=models.CharField(max_length=128)
    sup_pl5m=models.CharField(max_length=128)
    sup_pl6m=models.CharField(max_length=128)
    sup_sg1f=models.CharField(max_length=128)
    sup_sg2f=models.CharField(max_length=128)
    sup_sg3f=models.CharField(max_length=128)
    sup_sg4f=models.CharField(max_length=128)
    sup_sg5f=models.CharField(max_length=128)
    sup_sg6f=models.CharField(max_length=128)
    sup_pl1f=models.CharField(max_length=128)
    sup_pl2f=models.CharField(max_length=128)
    sup_pl3f=models.CharField(max_length=128)
    sup_pl4f=models.CharField(max_length=128)
    sup_pl5f=models.CharField(max_length=128)
    sup_pl6f=models.CharField(max_length=128)
    sup_sg1n=models.CharField(max_length=128)
    sup_sg2n=models.CharField(max_length=128)
    sup_sg3n=models.CharField(max_length=128)
    sup_sg4n=models.CharField(max_length=128)
    sup_sg5n=models.CharField(max_length=128)
    sup_sg6n=models.CharField(max_length=128)
    sup_pl1n=models.CharField(max_length=128)
    sup_pl2n=models.CharField(max_length=128)
    sup_pl3n=models.CharField(max_length=128)
    sup_pl4n=models.CharField(max_length=128)
    sup_pl5n=models.CharField(max_length=128)
    sup_pl6n=models.CharField(max_length=128)

    def __str__(self):
        return "{m}/{f}/{n}".format(m=self.pos_sg1m, f=self.pos_sg1f, n=self.pos_sg1n)


class VocGroup(models.Model):
    name=models.CharField(max_length=128)
    nounmembers=models.ManyToManyField(Noun)
    verbmembers=models.ManyToManyField(Verb)
    adjectivemembers=models.ManyToManyField(Adjective)

    def __str__(self):
        return self.name

VOCMODELS={0: Noun, 1: Verb, 2: Adjective}

Vokabel/forms.py
from django import forms

from .models import *

class AbstractVocForm(forms.ModelForm):
    class Meta:
        fields="__all__"

    vocgroups=forms.ModelMultipleChoiceField(VocGroup.objects.all(),
        widget=forms.widgets.SelectMultiple(attrs={"class": "selectpicker", "data-live-search": "true"}))

    def __init__(self, *args, **kwargs):
        if kwargs.get("instance"):
            initial = kwargs.setdefault("initial", {})
            initial["vocgroups"] = [t.pk for t in kwargs["instance"].vocgroup_set.all()]
        super(AbstractVocForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(AbstractVocForm, self).save(False)
        old_save_m2m = self.save_m2m
        def save_m2m():
           old_save_m2m()
           instance.vocgroup_set.clear()
           for group in self.cleaned_data["vocgroups"]:
               instance.vocgroup_set.add(group)
        self.save_m2m = save_m2m
        if commit:
            instance.save()
            self.save_m2m()
        return instance

class NounForm(AbstractVocForm):
    class Meta(AbstractVocForm.Meta):
        model=Noun

class VerbForm(AbstractVocForm):
    class Meta(AbstractVocForm.Meta):
        model=Verb

class AdjectiveForm(AbstractVocForm):
    class Meta(AbstractVocForm.Meta):
        model=Adjective

class VocGroupForm(forms.ModelForm):
    class Meta:
        model=VocGroup
        fields="__all__"

Vokabel/views.py
from django.db.models import Q
from django.shortcuts import render
from django.views import generic

from .forms import *

def searchAllFields(model, query):
	expr=Q()
	for field in model._meta.get_fields():
		if field.name == "vocgroup":
			expr=expr|Q(vocgroup__name__icontains=query)
		else:
			expr=expr|Q(**{field.name+"__icontains":query})
	return model.objects.filter(expr)

class MultipleModelsListView(generic.TemplateView):
	querysets={}    #context_object_name:getter method
	def get_context_data(self, **kwargs):
		ctx=super(MultipleModelsListView, self).get_context_data(**kwargs)
		for name, getter in self.querysets.items():
			ctx[name]=getter()
		return ctx

class AllVoc(MultipleModelsListView):
	template_name="index.html"
	querysets = {
		"nouns": Noun.objects.all,
		"verbs": Verb.objects.all,
		"adjectives": Adjective.objects.all
	}

class SearchView(generic.View):
	def get(self, request, *args, **kwargs):
		query=request.GET["query"]
		return render(request, "searchresults.html",
		    context={"nouns": searchAllFields(Noun, query),
		        "verbs": searchAllFields(Verb, query),
		        "adjectives": searchAllFields(Adjective, query)})

class AbstractCreateVoc(generic.CreateView):
	pass

class CreateNoun(AbstractCreateVoc):
	template_name = "noun_form.html"
	form_class = NounForm
	success_url = "/"

class NounDetail(generic.DetailView):
	template_name = "noun_detail.html"
	model = Noun

class CreateVerb(AbstractCreateVoc):
	template_name = "verb_form.html"
	form_class = VerbForm
	success_url = "/"

class VerbDetail(generic.DetailView):
	template_name = "verb_detail.html"
	model = Verb

class CreateAdjective(AbstractCreateVoc):
	template_name = "adjective_form.html"
	form_class = AdjectiveForm
	success_url = "/"

class AdjectiveDetail(generic.DetailView):
	template_name = "adjective_detail.html"
	model = Adjective


class CreateVocGroup(generic.CreateView):
	template_name = "vocgroup_form.html"
	form_class = VocGroupForm
	success_url = "/"

Vokabel/templates/form.html
{% extends 'layout.html' %}

{% block head %}
  {{ super() }}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css">
{% endblock %}

{% block content %}
  <h1 class="page-header">{% block header %}{% endblock %}</h1>
{#  {% if request.session.auto_add_vocgroup %}#}
{#    <h3>Hello, automatic add to Vocgroup {{ request.session.auto_add_vocgroup[1] }}</h3>#}
{#  {% endif %}#}
{##}
{#  <label for="vocgroup_select">Vocgroups</label>#}
{#  <select id="vocgroup_select" class="selectpicker" multiple data-live-search="true">#}
{#    <option>Lektion 1</option>#}
{#    <option>Lektion 2</option>#}
{#    <option>Lektion 3</option>#}
{#  </select>#}

{#  <ul id="vocgroup_list" class="list-group">#}
{#  </ul>#}
{#  <div class="form-group">#}
{#    <label for="vocgroup_select">VocGroup</label>#}
{#    <select id="vocgroup_select" class="form-control">#}
{#    </select>#}
{#  </div>#}
{#  <div class="form-group">#}
{#    <button class="btn btn-success" onclick="$('#vocgroup_list').append($('<li/>').addClass('list-group-item').html($('#vocgroup_select').val()))">Add</button>#}
{#  </div>#}

  <form action="{% block form_url %}{% endblock %}" method="post" role="form">
    {% csrf_token %}
    {{ form.vocgroups|bootstrap }}
    <div class="jumbotron">
      {% block helpers %}
      {% endblock %}
    </div>
    {% block form %}
    {% endblock %}
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>
{% endblock %}

{% block scripts %}
  {{ super() }}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>
{% endblock %}

Vokabel/templates/index.html
{% extends 'layout.html' %}

{% block head %}
  {{ super() }}
  <title>PyLatein - Latein-Trainer</title>
{% endblock %}

{% block cols %}
  <div class="col-lg-4 col-md-6 col-sm-12">
    <h1 class="page-header">All Nouns</h1>
    <table id="table_nomina" class="table table-striped table-hover">
      <tr>
        <th>Latin</th>
        <th>Translation</th>
      </tr>
      {% for noun in nouns %}
        <tr>
          <td><a href="{{ url('vokabel:view_noun', pk=noun.id) }}">{{ noun }}</a></td>
          <td>{{ noun.translation }}</td>
        </tr>
      {% endfor %}
    </table>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-12">
    <h1 class="page-header">All Verbs</h1>
    <table id="table_verbs" class="table table-striped table-hover">
      <tr>
        <th>Latin</th>
        <th>Translation</th>
      </tr>
      {% for verb in verbs %}
        <tr>
          <td><a href="{{ url('vokabel:view_verb', pk=verb.id) }}">{{ verb }}</a></td>
          <td>{{ verb.translation }}</td>
        </tr>
      {% endfor %}
    </table>
  </div>
  <div class="col-lg-4 col-md-6 col-sm-12">
    <h1 class="page-header">All Adjectives</h1>
    <table id="table_adjectives" class="table table-striped table-hover">
      <tr>
        <th>Latin</th>
        <th>Translation</th>
      </tr>
      {% for adjective in adjectives %}
        <tr>
          <td><a href="{{ url('vokabel:view_adjective', pk=adjective.id) }}">{{ adjective }}</a></td>
          <td>{{ adjective.translation }}</td>
        </tr>
      {% endfor %}
    </table>
  </div>
{% endblock %}

Vokabel/templates/noun_detail.html
{% extends 'layout.html' %}

{% block head %}
  {{ super() }}
	<title>View Noun - PyLatein</title>
{% endblock %}

{% block content %}
  <h3>{{ noun.sg1 }} [{{ noun.genus }}]</h3>
  <p>{{ noun.translation }}</p>
  <table class="table table-striped table-hover">
    <tr>
      <th></th>
      <th>Singular</th>
      <th>Plural</th>
    </tr>
    <tr>
      <th>1.</th>
      <td>{{ noun.sg1 }}</td>
      <td>{{ noun.pl1 }}</td>
    </tr>
    <tr>
      <th>2.</th>
      <td>{{ noun.sg2 }}</td>
      <td>{{ noun.pl2 }}</td>
    </tr>
    <tr>
      <th>3.</th>
      <td>{{ noun.sg3 }}</td>
      <td>{{ noun.pl3 }}</td>
    </tr>
    <tr>
      <th>4.</th>
      <td>{{ noun.sg4 }}</td>
      <td>{{ noun.pl4 }}</td>
    </tr>
    <tr>
      <th>5.</th>
      <td>{{ noun.sg5 }}</td>
      <td>{{ noun.pl5 }}</td>
    </tr>
    <tr>
      <th>6.</th>
      <td>{{ noun.sg6 }}</td>
      <td>{{ noun.pl6 }}</td>
    </tr>
  </table>
{% endblock %}

Vokabel/templates/noun_form.html
{% extends 'form.html' %}

{% block head %}
  {{ super() }}
	<title>Create Noun - PyLatein</title>
{% endblock %}

{% block header %}Create a new Noun!{% endblock %}
{% block form_url %}{{ request.path }}{% endblock %}

{% block helpers %}
  {{ form.declination|bootstrap }}
  {{ form.genus|bootstrap }}
  <div class="form-group">
    <label class="control-label" for="stem">Stem</label>
    <input type="text" class="form-control" id="stem" name="stem">
  </div>
  <div class="form-group">
    <input id="irreg_sg1" type="checkbox" aria-label="..." onclick="$('#irreg_group').slideToggle()">
    <label for="irreg_sg1">Irregular 1. Case Sg.?</label>
  </div>
  <div class="form-group" id="irreg_group">
    <label class="control-label" for="sg1">Nominative Sg.</label>
    <input type="text" class="form-control" id="sg1" name="sg1">
  </div>
  <div class="form-group">
    <input id="pl_only" type="checkbox" aria-label="...">
    <label for="pl_only">Plural only</label>
  </div>
  <div class="form-group">
    <button type="button" class="btn btn-default btn-lg" onclick="fill_form()">Fill!</button>
  </div>
{% endblock %}

{% block form %}
  {{ form.translation|bootstrap }}
  <table class="table table-bordered table-responsive">
    <tr>
      <th></th>
      <th>Singular</th>
      <th>Plural</th>
    </tr>
    <tr>
      <th>1.</th>
      <td>{{ form.sg1|bootstrap_inline }}</td>
      <td>{{ form.pl1|bootstrap_inline }}</td>
    </tr>
    <tr>
      <th>2.</th>
      <td>{{ form.sg2|bootstrap_inline }}</td>
      <td>{{ form.pl2|bootstrap_inline }}</td>
    </tr>
    <tr>
      <th>3.</th>
      <td>{{ form.sg3|bootstrap_inline }}</td>
      <td>{{ form.pl3|bootstrap_inline }}</td>
    </tr>
    <tr>
      <th>4.</th>
      <td>{{ form.sg4|bootstrap_inline }}</td>
      <td>{{ form.pl4|bootstrap_inline }}</td>
    </tr>
    <tr>
      <th>5.</th>
      <td>{{ form.sg5|bootstrap_inline }}</td>
      <td>{{ form.pl5|bootstrap_inline }}</td>
    </tr>
    <tr>
      <th>6.</th>
      <td>{{ form.sg6|bootstrap_inline }}</td>
      <td>{{ form.pl6|bootstrap_inline }}</td>
    </tr>
  </table>
{% endblock %}

{% block scripts %}
  {{ super() }}
  <script src="{{ static('js/grammar/decline.js') }}"></script>
	<script>
    function fill_form(){
      var sg1=$("#sg1").val();
      if (! $("#irreg_sg1").is(":checked")){
        sg1="__auto__";
      }
      var result=decline(sg1, $("#stem").val(),
        $("#id_genus").val(), $("#id_declination").val(), $("#pl_only").is(":checked"));
      for (var i = 0; i < cases.length; i++){
        $("#id_"+cases[i]).val(result[cases[i]]);
      }
    }
    function updateUI(){
      if (["C", "M", "I"].indexOf($("#id_declination").val()) > -1){
        $("#irreg_sg1").prop("checked", true);
        $("#irreg_group").slideDown();
      }
      else{
        $("#irreg_sg1").prop("checked", false);
        $("#irreg_group").slideUp();
      }
    }
    $(document).ready(function(){
      $("#irreg_group").slideUp(0);
      $("#id_declination").on("change", updateUI);
      updateUI();
    });
	</script>
{% endblock %} scripts %}

Vokabel/templates/searchresults.html
{% extends 'layout.html' %}

{% block head %}
  {{ super() }}
	<title>Search Results - PyLatein</title>
{% endblock %}

{% block cols %}
  <h1 class="page-header">Search results</h1>
  {% if nouns %}
    <div class="col-lg-4 col-md-6 col-sm-12">
      <h1 class="page-header">Nouns</h1>
      <table id="table_nomina" class="table table-striped table-hover">
        <tr>
          <th>Latin</th>
          <th>Translation</th>
        </tr>
        {% for noun in nouns %}
          <tr>
            <td><a href="{{ url('vokabel:view_noun', pk=noun.id) }}">{{ noun }}</a></td>
            <td>{{ noun.translation }}</td>
          </tr>
        {% endfor %}
      </table>
    </div>
  {% endif %}
  {% if verbs %}
  <div class="col-lg-4 col-md-6 col-sm-12">
    <h1 class="page-header">Verbs</h1>
    <table id="table_verbs" class="table table-striped table-hover">
      <tr>
        <th>Latin</th>
        <th>Translation</th>
      </tr>
      {% for verb in verbs %}
        <tr>
          <td><a href="{{ url('vokabel:view_verb', pk=verb.id) }}">{{ verb }}</a></td>
          <td>{{ verb.translation }}</td>
        </tr>
      {% endfor %}
    </table>
  </div>
  {% endif %}
  {% if adjectives %}
  <div class="col-lg-4 col-md-6 col-sm-12">
    <h1 class="page-header">Adjectives</h1>
    <table id="table_adjectives" class="table table-striped table-hover">
      <tr>
        <th>Latin</th>
        <th>Translation</th>
      </tr>
      {% for adjective in adjectives %}
        <tr>
          <td><a href="{{ url('vokabel:view_adjective', pk=adjective.id) }}">{{ adjective }}</a></td>
          <td>{{ adjective.translation }}</td>
        </tr>
      {% endfor %}
    </table>
  </div>
  {% endif %}
{% endblock %}

Vokabel/templates/vocgroup_form.html
{% extends 'layout.html' %}

{% block head %}
  {{ super() }}
  <title>Create Vocgroup - PyLatein</title>
{% endblock %}

{% block content %}
  <form method="post" action="{{ request.path }}" role="form">
    {% csrf_token %}
    {{ form|bootstrap }}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}